### ISSUE TITLE
Creating a debian package

### ISSUE THREAD

**Issue by alexmyczko** [swwa/audmes#1]
Hello swwa, for debian/copyright it would be helpful to have your full name and email address,
likewise with walter-schweitzer. Is that somehow possible?

For reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910876

Additionally it'd be great to have a manpage, desktop file and icon (like 256x256 instead of the 16x16 .ico)

**Comment by swwa** [comment]
@alexmyczko This repo is a mirror of the sourceforge repo. We have now swirched to Git on sourceforge.

**Comment by alexmyczko** [comment]
that'd be here https://sourceforge.net/p/audmes/git/ci/master/tree/ (for reference)

**Comment by swwa** [comment]
yes
