### ISSUE TITLE
Source duplication

### ISSUE THREAD

**Issue by alexmyczko** [swwa/audmes#2]
would it be possible to get rid of RtAudio/* and just use the system one instead?

would be great to get this solved for https://release.debian.org/bullseye/freeze_policy.html

**Comment by swwa** [comment]
@alexmyczko I prepared for it, but then I switched to pulseaudio on Linux and I had to use the latest RtAudio code and add a patch to support 192000 sample rate. I filed an issue https://github.com/thestk/rtaudio/issues/274.

**Comment by swwa** [comment]
The RtAudio issue is still open. Looks as if we have to live with the source duplication for now.
