### ISSUE TITLE
Ubuntu 20.04 - Missing dependency and no start

### ISSUE THREAD

**Issue by KastB** [swwa/audmes#3]
On Ubuntu 20.04 I had to additionally install  libpulse-dev
Maybe you can add that to the Readme?

After compilation the program won't start - without any output/error.

**Comment by swwa** [comment]
@KastB Thanks for the hint. I updated the README. Please check your sound card. You man need to plug in a cable.

**Comment by KastB** [comment]
You are right - it worked after plugging s.th. in.
It is kind of strange that it works now even if nothing is plugged in.
BTW: It's a notebook - so the internal devices should be available all the time...

**Comment by swwa** [comment]
@KastB Yes, the error handling of sound needs improvement. It is on the todo list.
