### ISSUE TITLE
libwxgtk3.0-dev fail

### ISSUE THREAD

**Issue by bobmc-rmm** [swwa/audmes#5]
bobmc@aorus:~/Desktop$ sudo apt install libwxgtk3.0-dev # libwxgtk3.0-gtk3-dev in Debian 11
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libwxgtk3.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libwxgtk3.0-dev' has no installation candidate

**Comment by swwa** [comment]
Hi Bob

In the comment after the "#" you see "libwxgtk3.0-gtk3-dev in Debian 11". So

  sudo apt install libwxgtk3.0-gtk3-dev

works for Debian 11. Maybe I have to make this clearer in the README.md.
